# Generated by Django 2.2.24 on 2024-03-19 09:35

from django.db import migrations


def define_new_buildings(apps, schema_editor):
    new_building_year_limit = 2015

    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year >= new_building_year_limit:
            flat.new_building = True
        else:
            flat.new_building = False
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(define_new_buildings,)
    ]
