# Generated by Django 2.2.24 on 2024-03-19 12:41

from django.db import migrations
from phonenumber_field.modelfields import PhoneNumber


def fill_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        owners_number = PhoneNumber.from_string(
            flat.owners_phonenumber,
            region='RU'
        )
        if owners_number.is_valid():
            flat.owner_pure_phone = owners_number
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20240319_1535'),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone)
    ]
