# Generated by Django 2.2.24 on 2024-03-19 14:09

from django.db import migrations


def fill_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            name=flat.owner,
            owner_pure_phone=flat.owner_pure_phone
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20240319_1656'),
    ]

    operations = [
        migrations.RunPython(fill_owners)
    ]
