# Generated by Django 2.2.24 on 2024-03-19 15:36

from django.db import migrations


def fill_owners_flats(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')

    for owner in Owner.objects.all():
        flats = Flat.objects.filter(owner=owner.name)
        owner.flats.set(flats)
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20240319_1723'),
    ]

    operations = [
        migrations.RunPython(fill_owners_flats)
    ]
